import { Language, StoreProduct, PodcastEpisode } from "./types";

export const LOCAL_TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    appTitle: "Patch It Zimbabwe",
    appSub: "Wellness Companion & Pain Relief Suite",
    selectStage: "Select Your Life-Stage Focus",
    cycleMode: "Cycle Mode (Youth Health)",
    recoveryMode: "Recovery Mode (Postpartum)",
    balanceMode: "Balance Mode (Menopause)",
    endoMode: "Endo Mode (Chronic Pelvic Pain)",
    changeStage: "Change Life Stage",
    welcomeTitle: "Comfort & Science Reclaiming Reproductive Health",
    welcomeDesc: "Welcome to Zimbabwe's first comprehensive wellness suite for Transdermal Patches, Thermal Belts, and indigenous traditional medicine.",
    
    // Reminders & Timers
    smartReminders: "Smart Patch & Gel Reminders",
    activeReminders: "Therapeutic Reminders",
    patchReminderLabel: "Replace Transdermal Patch (12h cycle)",
    gelReminderLabel: "Reapply Pain Relief Gel (6h cycle)",
    thermalTimer: "Thermal Therapy Belt Timer",
    thermalTimerDesc: "Protects your skin with guided 20-minute thermal exposure intervals.",
    minutes: "minutes",
    seconds: "seconds",
    startTimer: "Start Therapy Interval",
    pauseTimer: "Pause",
    resetTimer: "Reset",
    timerAlert: "Stop! 20 minutes completed. Remove thermal insert to protect your skin. Stay hydrated.",
    
    // Symptom Logger
    logSymptomTitle: "Symptom & Relief Logger",
    painIntensity: "Pain Intensity (Scale 1–10)",
    selectSymptoms: "What symptoms are you experiencing?",
    selectProducts: "Which Patch It products or indigenous remedies are you using?",
    notesPlaceholder: "Describe how you feel (you can speak or type in English, Shona or Ndebele...)",
    absenteeismLabel: "Did pain prevent attending school or work today?",
    submitting: "Analyzing Comfort Pipeline and Syncing...",
    submitBtn: "Log Symptoms & Generate AI Relief Pipeline",
    aiPipelineHeader: "Pain-to-AI Predictive Pipeline Feedback",
    detectedSymptom: "Detected Symptoms",
    absentRiskLabel: "School Absenteeism Risk",
    aiRemedies: "Comfort & Brewing Guidelines",
    aiProactiveTip: "Proactive Calendar Warning",
    
    // Lifecyle Modes
    cycleModeTitle: "Predicted Flower Flow & Absenteeism Avoidance Tracker",
    predictedCycle: "Predicted Cycle Flower Window",
    predictedCycleDesc: "Your physical cycle starts in 4 days. Optimal transdermal patch application is recommended on Sunday evening before school starts.",
    absenteeismDisclaimer: "Anonymized community data aggregates into our macro public health database to track menstrual health impacts across Zimbabwe.",
    
    postpartumTitle: "Postpartum Biological Healing Timeline",
    ppWeek: "Week",
    ppW1Title: "First Days of Rest & Involution",
    ppW1Desc: "Uterine involution begins. Minimize heavy lifting. Enjoy warm Makoni Tea twice daily to support pelvic core relaxation.",
    ppW3Title: "Lochia Transition & Elastic Healing",
    ppW3Desc: "Physical energy returns. Do not rush workouts. Practice deep horizontal breathing with the Heating Belt on mild warmth setting.",
    ppW6Title: "Pelvic Recovery Evaluation",
    ppW6Desc: "Muscle recovery progresses. Complete your daily gentle pelvic floor recovery routine to protect active strength.",
    gentleMovement: "Pelvic Floor Guided Audio Recovery",
    listenGuide: "Audio Exercise Guide (Low Bandwidth)",
    
    menopauseTitle: "Balance Space & Emergency Hot Flash Response",
    hotFlashBtn: "HOT FLASH EMERGENCY BUTTON (Kupisa Muviri)",
    hotFlashDesc: "Tap instantly to log hot flash trigger, initiate cooling belt routine, and capture night-sweat correlations.",
    hotFlashSuccess: "Emergency recorded. Please wrap your cooling-insert belt now, sit down, and drink iced Makoni tea.",
    sleepInsights: "Morning Sleep & Mood Baseline",
    sleepLabel: "How did your night sweats affect your sleep?",
    sleepBad: "Disrupted (Sweats)",
    sleepOk: "Partially Rested",
    sleepGood: "Restful Night",
    
    // Podcast Studio
    podcastStudio: "Podcast Studio & Indigenous Wellness Library",
    listenAesthetic: "Discreet Listening Mode Active",
    discreetTip: "All mental, uterine, and reproductive health tracks are labeled discreetly with subtle player art to protect your privacy.",
    downloadWifi: "Download for Offline (Save Bundles)",
    savedOffline: "Saved to Local Storage (100% Offline)",
    downloading: "Downloading Highly Compressed Audio...",
    traditionalLibrary: "Indigenous Wellness Encyclopedia",
    zumbaniTitle: "Zumbani (Lippia javanica) - Scientific Comfort",
    zumbaniDesc: "Rich in anti-inflammatory essential oils. Traditional brewing of the leaves alleviates deep core menstrual cramping, lowers light menopause fevers, and supports soothing postpartum tension.",
    makoniTitle: "Makoni (Myrothamnus flabellifolius) - Resilient Renewal",
    makoniDesc: "Zimbabwe's ancient 'resurrection bush'. Supports healthy blood circulation, balances hormonal stress levels, combats menopause night sweats, and clarifies vascular health.",
    
    // E-Commerce
    ecommerceTitle: "Subscription Reorder & Social Refill Store",
    paymentLabel: "Select Zimbabwean Mobile Coin Rail",
    buyOneGiftOne: "The 'Buy One, Gift One' Community Program",
    fundedTribe: "With every single order, you directly distribute free pain-management transdermal patches to under-resourced rural schools in Harare, Bulawayo, and beyond.",
    ruralImpactStats: "Anonymized Rural Girls Kept in School:",
    girlsCount: "1,420 girls protected",
    purchaseBtn: "Secure Refill Order",
    purchaseStatus: "Processing payment...",
    successOrder: "EcoCash/InnBucks Payment verified. Your refill is dispatched and 6 free patch packages are shipped to Mashonaland rural school girls!",
    
    // Emulator Labels
    telecomEmulator: "Unified Zimbabwe Telecom Gateway",
    ussdSubtitle: "Stateful USSD (*123#) Offline Dial-in Simulator",
    ussdWarning: "USSD services function completely offline without data bundles on dumb-phones.",
    whatsappSubtitle: "WhatsApp AI Sister Chatbot Gateway (+263 77 123 4567)",
    whatsappPrompt: "Type system queries in Shona or Ndebele (e.g. 'musana uri kurwadza')",
    unifiedDbTitle: "Unified PostgreSQL Real-time Active Database State Viewer",
    channelLabel: "Incoming Source Channel",
    dbLogsCount: "Unified logs tracked",
    dialNow: "Dial *123#",
    resetUssd: "Reset Session",
    sendWhatsapp: "Send",
    enterInput: "Enter Option"
  },
  sn: {
    appTitle: "Patch It Zimbabwe",
    appSub: "Mufambidzani Wehutano nekuZorora Marwadzo",
    selectStage: "Sarudzai Danho reHutano Hwenyu",
    cycleMode: "Cycle Mode (Vechidiki neMenstruation)",
    recoveryMode: "Recovery Mode (Pashure peKubereka)",
    balanceMode: "Balance Mode (Kuguma Kutevera / Menopause)",
    endoMode: "Endo Mode (Marwadzo eChiuno & Endo)",
    changeStage: "Chinja Danho reHutano",
    welcomeTitle: "Kuzorora neSainzi Kusimudzira Hutano Hwemadzimai",
    welcomeDesc: "Gamuchirai kuongororo yekutanga muZimbabwe yezvigamba zvemarwadzo (Patches), bhandi remagetsi (Thermal Belt), nemishonga yechinyakare.",
    
    // Reminders & Timers
    smartReminders: "Zviyeuchidzo zveZvigamba neMafuta",
    activeReminders: "Zviyeuchidzo zvekubatsira muviri",
    patchReminderLabel: "Chinja Chigamba Chemarwadzo (Maawa gumi nemaviri)",
    gelReminderLabel: "Zora Mafuta Anozorodza Marwadzo (Maawa matanhatu)",
    thermalTimer: "Bhandi Rekudziya (Thermal Belt) Timer",
    thermalTimerDesc: "Kuchengetedza ganda rako parutsva nekushandisa kwemaminetsi makumi maviri chete.",
    minutes: "maminetsi",
    seconds: "masekonzi",
    startTimer: "Tanga Kudziisa Bhandi",
    pauseTimer: "Misa",
    resetTimer: "Zvitangise",
    timerAlert: "Stop! Maminetsi 20 akwana. Bvisa bhandi pamuviri kudzivirira ganda. Inwa mvura yakawanda.",
    
    // Symptom Logger
    logSymptomTitle: "Kunyorwa kweMarwadzo neChirwere",
    painIntensity: "Kuoma kweMarwadzo (Scale 1–10)",
    selectSymptoms: "Ndezvipi zviratidzo zvauri kunzwa mumuviri?",
    selectProducts: "Ndezvipi zvigamba kana tiye yechinyakare yauri kushandisa?",
    notesPlaceholder: "Tsanangura manzwiro auri kuita (unogona kunyora neShona, Ndebele kana English...)",
    absenteeismLabel: "Ko marwadzo aya akakutadzisa kuenda kuchikoro kana kubasa nhasi?",
    submitting: "Kutumira Mashoko nekuGadzira AI Relief...",
    submitBtn: "Nyora Marwadzo nekuGadzira AI Relief Guide",
    aiPipelineHeader: "Mhinduro Kubva kuPain-to-AI Pipeline",
    detectedSymptom: "Zviratidzo Zvaonekwa neAI",
    absentRiskLabel: "Ngozi Yokusara kuChikoro",
    aiRemedies: "Maitiro Ekuvhura Ndiro yeZumbani nePatch",
    aiProactiveTip: "Yambiro yePredictive Calendar",
    
    // Lifecycle Modes
    cycleModeTitle: "Kufungidzira Kutevera & Kudzivirira Kurara kumba kweVana veChikoro",
    predictedCycle: "Kufungidzira Kutevera Unotevera",
    predictedCycleDesc: "Kutevera kwako kuchatanga mumazuva mana. Zviri nani kunamira chigamba (transdermal patch) neSvondo manheru chikoro chisati chatanga.",
    absenteeismDisclaimer: "Mashoko ako anochengetwa pachivande uye anounganidzwa kuratidza dambudziko rekushaya zvigadziriso muZimbabwe.",
    
    postpartumTitle: "Matanho Ekupora Kwemuviri Pashure peKubereka",
    ppWeek: "Vhiki",
    ppW1Title: "Mazuva Ekutanga: Kuzorora nekudzoka kweChibereko",
    ppW1Desc: "Chibereko chiri kudzokera parugare. Usasimudza zvinorema. Inwa tiye yeMakoni inopisa kaviri pazuva.",
    ppW3Title: "Kuchinja kweLochia neKupora kweGanda",
    ppW3Desc: "Simba riri kudzoka zvinyoro nyoro. Zorera mafuta anozorodza. Shandisa bhandi redziya rakaderera.",
    ppW6Title: "Kuongororwa Kwekupora kweChibereko neMusana",
    ppW6Desc: "Mhasuru dzechiuno dzava kupora. Ita maekisesaizi emuviri anoitwa pashure pekubara zuva nezuva.",
    gentleMovement: "Maekisesaizi eChiuno: Guided Audio",
    listenGuide: "Maitiro aungateerera pasina data rakawanda",
    
    menopauseTitle: "Nzvimbo neKugadzirisa Emergency yeHot Flash",
    hotFlashBtn: "HOT FLASH EMERGENCY BUTTON (Kupisa Muviri)",
    hotFlashDesc: "Dzvanya izvozvi kana muviri uchingopisa kamwe kamwe, unyore dambudziko uye utore bhandi rekutonhodza.",
    hotFlashSuccess: "Dambudziko ranyorwa muDatabase athu. Zora mafuta anotonhodza kana kugeza kumeso, unwe tiye yeMakoni inotonhorera.",
    sleepInsights: "Kuongorora Khope neManzwiro eMangwanani",
    sleepLabel: "Ko kupisa muviri husiku kwakakanganisa seiko hope dzenyu?",
    sleepBad: "Hadzo dzakanaka (Kupisa Muviri)",
    sleepOk: "Kamboita nani",
    sleepGood: "Dzakanaka kwazvo",
    
    // Podcast Studio
    podcastStudio: "Podcast Studio neLibrary yeMishonga yeChinyakare",
    listenAesthetic: "Maitiro ekuteerera Chinyararire (Discreet Listen)",
    discreetTip: "Zvirongwa zvese zvehutano hwevakadzi zvinoratidzwa nemazita asiri ekushusha kuitira kuchengeta chakavanzika chako.",
    downloadWifi: "Dhawunirodha uchengete Data bhanduru",
    savedOffline: "Zvatosvitswa muFoni mako (Offline 100%)",
    downloading: "Kudhawunirodha zvinyoro-nyoro pasina data...",
    traditionalLibrary: "Duramazwi reMishonga yeChinyakare",
    zumbaniTitle: "Zumbani (Lippia javanica) - Chiratidzo cheKuzorora",
    zumbaniDesc: "Ine mafuta anorwisa kuzvimba. Kubika mashizha eZumbani kunopedza marwadzo ekuenda kumwedzi (cramps), kudzikisa kupisa kwemuviri wekuguma kutevera, nekunyaradza muviri wakasuruvara.",
    makoniTitle: "Makoni (Myrothamnus flabellifolius) - Simudzira Mweya",
    makoniDesc: "Inozivikanwa nemazita echinyakare muZimbabwe. Inobatsira kufamba zvakanaka kweropa, kudzikisa hormonal stress, kudzivirira kupisa muviri husiku nekugadzirisa tsinga.",
    
    // E-Commerce
    ecommerceTitle: "Kuodha patsva neRefills kuChitoro Chedu",
    paymentLabel: "Sarudzai Nzira Ikubhadhara muZimbabwe",
    buyOneGiftOne: "Chirongwa che 'Buy One, Gift One' svedu",
    fundedTribe: "Paunotenga refill rimwe chete remurwere, unoita kuti isu tipe zvigamba zvemahara kune vana vechikoro vekumaruwa muHarare neBulawayo.",
    ruralImpactStats: "Vana vekumaruwa vakachengetwa kuchikoro:",
    girlsCount: "Vana gumi nezvisere vechikoro vanodzivirirwa",
    purchaseBtn: "Simbisa Kuodha Kwako",
    purchaseStatus: "Kugadzira kubhadharisa...",
    successOrder: "EcoCash/InnBucks kubhadharisa kwaitika! Takuendeserai zvigamba zvenyu, uye tatumira mapaketi embedded kune vana vekumaruwa mahara!",
    
    // Emulator Labels
    telecomEmulator: "Zimbabwe Telecom Gateways (E-Simulators)",
    ussdSubtitle: "Stateful USSD (*123#) Yeparunhare Yepasi",
    ussdWarning: "USSD inoshanda pasina data bhanduru pane chero runhare rwekale.",
    whatsappSubtitle: "WhatsApp AI Sister Chatbot (+263 77 123 4567)",
    whatsappPrompt: "Nyorai mibvunzo yenyu mumutauro weShona kana Ndebele...",
    unifiedDbTitle: "PostgreSQL Database real-time (Unified active state)",
    channelLabel: "Mugero Unopinda Mvura",
    dbLogsCount: "Unified data ranyorwa",
    dialNow: "Dzvanya *123#",
    resetUssd: "Reset Session",
    sendWhatsapp: "Tumira",
    enterInput: "Isa sarudzo"
  },
  nd: {
    appTitle: "Patch It Zimbabwe",
    appSub: "Umngane Wezempilakahle loKuphelisa Ubuhlungu",
    selectStage: "Khetha Isigaba Sakho Sezempilakahle",
    cycleMode: "Cycle Mode (Intsha leMenses)",
    recoveryMode: "Recovery Mode (Ngemva Kokuzala)",
    balanceMode: "Balance Mode (Menopause / Ukuphelelwa)",
    endoMode: "Endo Mode (Ubuhlungu be-Endo le-Pelvic)",
    changeStage: "Guqula Isimo Bezempilakahle",
    welcomeTitle: "Ukuzola loSuku lokuthuthuka kwabesifazane",
    welcomeDesc: "Wamukelekile kuhlolo lokuqala eZimbabwe lokuphunguza ubuhlungu ngezichibi (Patches), ibhanti lokufudumala, lemithi yemvelo yesintu.",
    
    // Reminders & Timers
    smartReminders: "Izikhumbuzo zezichibi lamafutha",
    activeReminders: "Izikhumbuzo zokusiza umzimba",
    patchReminderLabel: "Tshintsha Isichibi Sobuhlungu (Emasontweni ayi-12)",
    gelReminderLabel: "Gcobha Amafutha Okudambisa Ubuhlungu (Amahora ayi-6)",
    thermalTimer: "Ibhanti Lokufudumeza (Thermal Belt) Timer",
    thermalTimerDesc: "Vikela isikhumba sakho ngemizuzu engu-20 kuphela yokufudumeza.",
    minutes: "imizuzu",
    seconds: "imizuzwana",
    startTimer: "Qala Ukufudumeza",
    pauseTimer: "Misa kancane",
    resetTimer: "Zithungise",
    timerAlert: "Stop! Imizuzu engu-20 isiphelile. Susa ibhanti kumzimba wakho ukuvikela isikhumba. Inwa amanzi amaningi.",
    
    // Symptom Logger
    logSymptomTitle: "Ukubhalwa kwayo Yonke Imisebenzi Yomzimba",
    painIntensity: "Ubuhlungu obuzwayo (Scale 1–10)",
    selectSymptoms: "Yiziphi izibonakaliso ozizwayo emzimbeni wakho?",
    selectProducts: "Yiziphi izichibi kumbe amayezi esintu owasebenzisayo?",
    notesPlaceholder: "Chasisa indlela ozizwa ngayo (ungabhala ngesiNdebele, Shona kumbe English...)",
    absenteeismLabel: "Kambe ubuhlungu lobu bukwenze waphutha esikoleni loba emsebenzini lamuhla?",
    submitting: "Ukusindisa Imininingwane lokusebenzisa i-AI...",
    submitBtn: "Bhala Phansi Ubuhlungu lokugaya i-AI Analysis",
    aiPipelineHeader: "Mpendulo evela ku-Pain-to-AI Pipeline",
    detectedSymptom: "Izibonakaliso ezitholiweyo nge-AI",
    absentRiskLabel: "Ingozi Yokulahlekelwa Isikolo",
    aiRemedies: "Indlela Yokusebenzisa Itiye leZumbani lesichibi",
    aiProactiveTip: "Isixwayiso Sekhalenda Elandelayo",
    
    // Lifecycle Modes
    cycleModeTitle: "Ukuqagela Ikhalenda & Ukuvikela Abantwana Ekulahlekelweni Isikolo",
    predictedCycle: "Ukuqagela Isikhathi Se-Flower Flow",
    predictedCycleDesc: "Isikhathi sakho sizongena ngemva kwezinsuku ezi-4. Isikhumbuzo sokunamathisela isichibi ngesonto kusihlwa silungisiwe ukuzovikela isikolo.",
    absenteeismDisclaimer: "Imininingwane yakho igcinwa ngasese ukuze sibone ubunzima obubhekene labantwana basesigabeni sakithi e-Zimbabwe.",
    
    postpartumTitle: "Matanho Okwelatshwa Ngemva Kokubeletha",
    ppWeek: "Iviki",
    ppW1Title: "Izinsuku Zokuqala: Ukupumula loKuncipha kwebhande",
    ppW1Desc: "Isizalo siyaqala ukubuyela endaweni yaso. Ungaphakamisi izinto ezisindayo. Inwa itiye yeMakoni eshisayo kabili ngosuku.",
    ppW3Title: "Ukuhlangana kweLochia leGazi Lokuhlanza",
    ppW3Desc: "Amandla omzimba ayaqala ukubuya. Gcobha amafutha okukhulula amalunga emilenze. Sebenzisa ibhanti lokushisa phansi.",
    ppW6Title: "Ukuphola Komzimba lokuvuselelwa Kwesizalo",
    ppW6Desc: "Imisipha yeqolo isiqala ukuphola. Qeda ukwenza amaekisesaizi embelekweni ngosuku lwanamuhla.",
    gentleMovement: "Pelvic Floor Guided Exercises (Audio)",
    listenGuide: "Lalela kakuhle ngaphandle kwedata enengi",
    
    menopauseTitle: "Ukunonophisa Phakathi Kwenkinga ye-Hot Flash",
    hotFlashBtn: "HOT FLASH EMERGENCY BUTTON (Kutshisa Komzimba)",
    hotFlashDesc: "Cindezela lapha nxa umzimba utshisa ngokuzumayo ukuze ubhale ukutshisa lokho kuku-database.",
    hotFlashSuccess: "Inkinga isibhaliwe ku-database. Namathisela isichibi esi-cooling sebhanti lokufudumala, inwa itiye yeMakoni ebandayo.",
    sleepInsights: "Morning Sleep & Mood Evaluation",
    sleepLabel: "Ko ukutshisa komzimba ebusuku kukuthinte njani ukulala kwakho?",
    sleepBad: "Kuhluphile kakhulu (Sweats)",
    sleepOk: "Kubo ngconywana",
    sleepGood: "Ngilale kahle kakhulu",
    
    // Podcast Studio
    podcastStudio: "Podcast Studio leWadi Yemithi Yesintu yeZumbani loMakoni",
    listenAesthetic: "Indlela Yokulalela Ngasese (Discreet Listening)",
    discreetTip: "Zonke izinhlelo zezempilakahle zibhalwa ngendlela efihlakeleyo ukuzovikela ukuhlekelwa ngabanye emiphakathini yethu.",
    downloadWifi: "Dhawuniloda ngemali encane kumbe Wi-Fi",
    savedOffline: "Kugcinwe efonini yakho (Offline 100%)",
    downloading: "Kudhawunilodwa ngaphandle kokudla idata enengi...",
    traditionalLibrary: "IWadi Yemithi Wesintu loMvelo yesizwe",
    zumbaniTitle: "Zumbani (Lippia javanica) - Ukuzola LoMoya Omhle",
    zumbaniDesc: "Ilesithako esilwa lokubambeka komzimba. Ukupheka amapepa eZumbani kuqeda ubuhlungu be-period, yehlisa ukutshisa komzimba ngesikhathi se menopause.",
    makoniTitle: "Makoni (Myrothamnus flabellifolius) - Ukuphila Kutsha",
    makoniDesc: "Umuthi wesintu we-resurrection bush edumileyo e-Zimbabwe. Unceda igazana ukuthi lihambe kahle, wehlise i-hormonal stress le-night sweats.",
    
    // E-Commerce
    ecommerceTitle: "Ukuthenga i-Refill yezichibi esitolo sethu",
    paymentLabel: "Khetha indlela yokubhadhara eZimbabwe",
    buyOneGiftOne: "Inhlelo ka 'Buy One, Gift One' yethu",
    fundedTribe: "Nxa uthenga iphakethe lobuhlungu, wenza ukuthi siphe abantwana basesigabeni esingaphandle kwamaphakethe we mahala basesimeni semenses.",
    ruralImpactStats: "Abantwana basesigabeni esingaphandle abavikela isikolo:",
    girlsCount: "Abantwana abayi-1,420 bavikelwe",
    purchaseBtn: "Simbisa Ukuthenga Kwakho",
    purchaseStatus: "Kubhadhariswa khathesi...",
    successOrder: "EcoCash/InnBucks kubhadharwa kuphelile! Sikuthumelele amaphakethe akho, amanye amaphakethe angu-6 asethunyelwe emaphandleni mahala!",
    
    // Emulator Labels
    telecomEmulator: "Uzulu Telecom E-Gateways Zimbabwe",
    ussdSubtitle: "Stateful USSD (*123#) Offline Dial-in Simulator",
    ussdWarning: "USSD isebenza ngokukhululekileyo ngaphandle kobandulo bwe-Data kumafoni amadala.",
    whatsappSubtitle: "WhatsApp AI Sister Chatbot (+263 77 123 4567)",
    whatsappPrompt: "Bhala izibonakaliso zomzimba wakho ngesintu...",
    unifiedDbTitle: "PostgreSQL Database state view (Real-time updates)",
    channelLabel: "Incoming channel path",
    dbLogsCount: "Imininingwane ebhaliweyo",
    dialNow: "Ganyula *123#",
    resetUssd: "Reset Session",
    sendWhatsapp: "Thumela",
    enterInput: "Khetha Isinqumo"
  }
};
